
[platformio]
default_envs = manual-lite

[env:manual-lite]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  olikraus/U8g2 @ ^2
build_flags =
  -DUI_OLED=1
  -DOLED_SDA=21
  -DOLED_SCL=22
  -DROT_ENC_A=32
  -DROT_ENC_B=33
  -DROT_BTN=25
  -DTRIGGER_BTN=27
  -DSSR_PIN=26
  -DPEN_SW_PIN=14
  -DPREHEAT_MIN_MS=1
  -DPREHEAT_MAX_MS=6
  -DMAIN_MIN_MS=4
  -DMAIN_MAX_MS=40
