
[env:manual-lite]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  olikraus/U8g2 @ ^2
build_flags =
  -DOLED_SDA=21
  -DOLED_SCL=22
  -DOLED_ADDR=0x3C
  -DENC_A=32
  -DENC_B=33
  -DENC_BTN=25
  -DTRIG_BTN=27
  -DSSR_PIN=26
  -DBUZZER_PIN=19
  -DPULSE_MIN_MS=4
  -DPULSE_MAX_MS=60
  -DPREHEAT_MAX_MS=10
  -DDELAY_MAX_MS=40
